<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputPath>..\NopStation.Plugin.Misc.Core</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <Version>4.70.1.0</Version>
    <Authors>Nop-Station Team, Jaber Kibria</Authors>
    <Company>Nop-Station</Company>
    <Product>Nop-Station Actions</Product>
    <AssemblyVersion>4.70.1.0</AssemblyVersion>
    <FileVersion>4.70.1.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Description>This plugin is used to manage Nop-Station plugins.</Description>
    <Copyright>Nop-Station Team</Copyright>
    <PackageTags>NopStation,Core,NopCommerce,Plugin</PackageTags>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <RootNamespace>NopStation.Plugin.Misc.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Filters\LicenseAttribute.cs" />
    <Compile Remove="Filters\NopStationPublicLicenseAttribute.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Nop.Core\Nop.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Data\Nop.Data.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Services\Nop.Services.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web\Nop.Web.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="release_note.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />
    <!-- Delete extra folders and files from plugin output directory -->
    <RemoveDir Directories="$(OutDir)\refs;$(OutDir)\ref" />
    <Delete Files="$(OutDir)\$(AssemblyName).deps.json;$(OutDir)\$(AssemblyName).pdb;$(OutDir)\$(AssemblyName).staticwebassets.runtime.json" />
  </Target>

</Project>
