<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <OutputPath>..\..\Presentation\Nop.Web\Plugins\NopStation.Core</OutputPath>
    <OutDir>$(OutputPath)</OutDir>
    <Version>4.70.1.0</Version>
    <Authors>Nop-Station Team, Jaber Kibria</Authors>
    <Company>Nop-Station</Company>
    <Product>Nop-Station Core</Product>
    <AssemblyVersion>4.70.1.0</AssemblyVersion>
    <FileVersion>4.70.1.0</FileVersion>
    <NeutralLanguage>en</NeutralLanguage>
    <Description>This plugin is used to manage Nop-Station plugins.</Description>
    <Copyright>Nop-Station Team</Copyright>
    <PackageTags>NopStation,Core,NopCommerce,Plugin</PackageTags>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Domain\**" />
    <Compile Remove="Factories\**" />
    <Compile Remove="Views\Shared\Components\**" />
    <Content Remove="Domain\**" />
    <EmbeddedResource Remove="Domain\**" />
    <EmbeddedResource Remove="Factories\**" />
    <EmbeddedResource Remove="Views\Shared\Components\**" />
    <None Remove="Domain\**" />
    <None Remove="Factories\**" />
    <None Remove="Views\Shared\Components\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Models\PluginListModel.cs" />
    <Compile Remove="Models\PluginModel.cs" />
    <Compile Remove="Models\PluginSearchModel.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="logo.png" />
    <None Remove="Views\NopStationCore\Permissions.cshtml" />
    <None Remove="Views\Plugin\List.cshtml" />
    <None Remove="Views\Shared\EditorTemplates\Select2Category.cshtml" />
    <None Remove="Views\Shared\EditorTemplates\Select2Manufacturer.cshtml" />
    <None Remove="Views\Shared\EditorTemplates\Select2Product.cshtml" />
    <None Remove="Views\Shared\EditorTemplates\Time.cshtml" />
    <None Remove="Views\Shared\EditorTemplates\TimeNullable.cshtml" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Views\NopStationCore\Configure.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\NopStationCore\LocaleResource.cshtml" />
    <Content Include="Views\NopStationCore\AssemblyInfo.cshtml" />
    <Content Include="Views\NopStationCore\Permissions.cshtml" />
    <Content Include="Views\NopStationLicense\License.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Plugin\List.cshtml">
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Views\Shared\EditorTemplates\Select2Category.cshtml" />
    <Content Include="Views\Shared\EditorTemplates\Select2Manufacturer.cshtml" />
    <Content Include="Views\Shared\EditorTemplates\Select2Product.cshtml" />
    <Content Include="Views\Shared\EditorTemplates\Time.cshtml" />
    <Content Include="Views\Shared\EditorTemplates\TimeNullable.cshtml" />
    <None Include="Views\Shared\Components\ManagePlugins\Default.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\Nop.Core\Nop.Core.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Data\Nop.Data.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Libraries\Nop.Services\Nop.Services.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web.Framework\Nop.Web.Framework.csproj">
      <Private>false</Private>
    </ProjectReference>
    <ProjectReference Include="..\..\Presentation\Nop.Web\Nop.Web.csproj">
      <Private>false</Private>
      <CopyLocal>False</CopyLocal>
    </ProjectReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="NopStation.Plugin.Misc.Actions">
      <HintPath>NopStation.Plugin.Misc.Actions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="RestSharp">
      <HintPath>..\NopStation.Plugin.Misc.Core\dll\RestSharp.dll</HintPath>
      <CopyLocal>True</CopyLocal>
    </Reference>
    <Reference Include="Jwt">
      <HintPath>..\NopStation.Plugin.Misc.Core\dll\Jwt.dll</HintPath>
      <CopyLocal>True</CopyLocal>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Update="Views\BuilderProduct\AttributeMappingProduct.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\BuilderProduct\Details.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\BuilderProduct\ProductDetails.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\BuilderProduct\_CatalogSelectors.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\BuilderProduct\_ProductBox.ProductBuilder.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\NopStationCore\Permissions.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\NopStationCore\AssemblyInfo.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\NopStationCore\LocaleResource.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\Shared\EditorTemplates\Select2Product.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\Shared\EditorTemplates\Select2Manufacturer.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\Shared\EditorTemplates\Select2Category.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\Shared\EditorTemplates\Time.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\Shared\EditorTemplates\TimeNullable.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Views\_ViewImports.cshtml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Update="contents\css\style.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="contents\fonts\icomoon.eot">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="contents\fonts\icomoon.svg">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="contents\fonts\icomoon.ttf">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="contents\fonts\icomoon.woff">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="contents\style.css">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Microsoft.OpenApi.dll">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="plugin.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="release_note.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ClearPluginAssemblies Include="$(MSBuildProjectDirectory)\..\..\Build\ClearPluginAssemblies.proj" />
  </ItemGroup>

  <!-- This target execute after "Build" target -->
  <Target Name="NopTarget" AfterTargets="Build">
    <!-- Delete unnecessary libraries from plugins path -->
    <MSBuild Projects="@(ClearPluginAssemblies)" Properties="PluginPath=$(MSBuildProjectDirectory)\$(OutDir)" Targets="NopClear" />

    <!-- Delete extra folders and files from plugin output directory -->
    <RemoveDir Directories="$(OutDir)\refs;$(OutDir)\ref" />
    <Delete Files="$(OutDir)\$(AssemblyName).deps.json;$(OutDir)\$(AssemblyName).pdb;$(OutDir)\$(AssemblyName).staticwebassets.runtime.json" />
  </Target>

</Project>
